services:
    # nginx
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./backend/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        # networks:
        #   - app

    # php
    backend:
        build:
            dockerfile: ./backend/Dockerfile
        volumes:
            - /var/www/html/vendor
            - ./backend/app:/var/www/html/
        # networks:
        #   - app
        

    # mysql
    db:
        image: mysql:8.0
        volumes:
            - "./backend/sql:/docker-entrypoint-initdb.d"
        ports:
            - "4406:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
        # networks:
        #   - app

     # react
    frontend:
      build:
        dockerfile: ./frontend/Dockerfile
      tty: true
      ports:
        - 3000:3000
      volumes:
        - ./frontend/src:/src  
      # networks:
      #   - app


# networks:
#   app:
#     driver: bridge